### ISSUE TITLE
Bandeau adaptatif aux données sélectionnées par l'emprise de la carte

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#24]
**Description** : Afficher des informations adaptées aux données enregistrées dans l'emprise affichée de la carte
**User Voice** : En tant qu'utilisateur, je veux disposer des informations statistiques de l'emprise affichée sur la carte
**Tests de conformité** : 
 1- Au chargement de l'appli, vérifier que le bandeau affiche des statistiques pour toutes les données (tout rennes métropole)
 2- Si je zoome sur la carte, alors le bandeau est mis à jour pour n'afficher que les données de la zone zoomée
 3- Si je valide une ZAC, alors le bandeau est mis à jour pour n'afficher que les données de la ZAC sélectionnée
 4- Si je filtre sur un moyen de transport, alors le bandeau est mis à jour pour n'afficher que les données de la ZAC sélectionnée ou de l'emprise de la carte filtrées sur le moyen de transport sélectionné 
 5- Si choisis un jour, alors le bandeau est mis à jour pour n'afficher que les données de la ZAC sélectionnée ou de l'emprise de la carte filtrées sur le jour choisi

**Comment by Gaetanbrl** [comment]
Nécessite la création du module #32

**Comment by Gaetanbrl** [comment]
Les boutons +, home, - seront déplacés pour ne pas être sous le template.
Le template étant fixe, cela ne pausera pas de soucis dans cette version.

**Comment by Gaetanbrl** [comment]
* Selon une ZAC
- [ ] Création d'une couche ZAC vide
- [ ] Interrogation CQL de la couche ZAC #5 au déplacement de la carte (ZAC contains Map Center)
- [ ] Récupération des données d'enquête selon l'entité ZAC parcourue
- [ ] Affichage des données brut dans le volet latéral d'infos

* Selon l'emprise
- [ ] Récupération des coordonnées l'emprise de la carte (bbox)
- [ ] Transformation des coordonnées de l'emprise en géométrie (via librairie turf.js déjà ajoutée comme extension Mviewer)
- [ ] Interrogation CQL des données d'enquête avec l'emprise (bbox geom contains data)
- [ ] Affichage des données brut dans le volet latéral d'infos

**Comment by Gaetanbrl** [comment]
Nouvelles tâches en cours :
- [ ] Intégrer les interfaces pour le reste du volet d'information
- [ ] Filtrage du layer par temps / horaire #18 
- [ ] Filtrage du layer par mode de transport #17 
- [ ] Intégration du graphique sur les données à l'écran
- [ ] Affichage des données dans le volet à l'initialisation de la carte
- [ ] Maj des infos textuelles
![image](https://user-images.githubusercontent.com/16317988/88818872-81829980-d1bf-11ea-9267-449a05182624.png)
- [ ] Affichage du nombre de saisies
- [ ] Affichage du nombre d'absents ou télétravail
- [ ] Insertion des interfaces pour la saisie et des infos et de connexion

* L'insertion des interfaces permet d'intégrer les interfaces selon la maquette, mais la fonctionnalité n'est pas encore développée.

**Comment by Gaetanbrl** [comment]
"Englobe" #17 et #18 et #15

**Comment by cbriand** [comment]
OK, le bandeau s'adapte correctement aux valeurs de la carte et aux filtres (données de l'emprise ou de la zac)
